### ISSUE TITLE
Support for custom asset types

### ISSUE THREAD

**Issue by orionrush** [samrith-s/parcel-plugin-structurize#1]
It appeared to me that I could add a custom file type handler by simply incorporating the following into my `package.json` file like so:

```
"parcel-plugin-structurize": {
    "fonts": {
            "match": "*.{eto,woff,ttf}",
            "folder": "fonts"
        }
}
```

Is there a way to extend structurize to support abitrary file types?

**Comment by samrith-s** [comment]
Hey @orionrush, atm not any way I can think off. But I think what you could do, is just add a new structurer which gets called. 

Check out this folder https://github.com/samrith-s/parcel-plugin-structurize/tree/master/src/structurers

**Comment by samrith-s** [comment]
Closing due to no response. Feel free to reopen if you have any more queries.
