### ISSUE TITLE
Doesn't change paths in html files

### ISSUE THREAD

**Issue by dreit-p** [samrith-s/parcel-plugin-structurize#14]
Hello! Can you explain me, what is wrong do i do?
Paths of the resources don't change in html files when i do build. I get structured files, but in the html files still flat paths.
Repo: [https://github.com/dreit-p/for-parcel-structurize](https://github.com/dreit-p/for-parcel-structurize)

**Comment by samrith-s** [comment]
Hey, so sorry for the delay. I have been very busy with work. I will have a look at this over the weekend, and get back to you. :)

Also, could you quickly tell me what paths don't change in the HTML file?

**Comment by dreit-p** [comment]
After structuring, file links in html files remain as if they were in the flat structure.
And thank you for your attention :)

**Comment by samrith-s** [comment]
Hey,

Got it. I have pushed a fix for this in [v1.1.16](https://github.com/samrith-s/parcel-plugin-structurize/releases/tag/v1.1.6). Do let me know if it solves it for you. It works for me! :)

**Comment by samrith-s** [comment]
Closing due to no response.
