### ISSUE TITLE
Windows 10 Build

### ISSUE THREAD

**Issue by Askerx9** [samrith-s/parcel-plugin-structurize#15]
Hello,

When I run "parcel build ./src/**/*.html" and parcel-plugin-structize is configured, it also rewrites my HTML files in the src folder but only on Windows 10, not on Mac or Linux.

Do you already have the problem? Do you have a solution?

Thank you for reading me and for your time :)

**Comment by samrith-s** [comment]
Hey Askerx,

That's very weird. No, it doesn't happen to me. Can you provide me with your setup? 

The plugin relies on the files provided by Parcel bundler, which we get here:https://github.com/samrith-s/parcel-plugin-structurize/blob/master/src/index.js#L36

If it is so, then I think it should be an issue filed with Parcel. Can you also try specifying a single HTML entry file, and not a glob?
