### ISSUE TITLE
 UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by IsaacHub** [samrith-s/parcel-plugin-structurize#19]
While building I got the following warning in the console: 

```
(node:24764) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)

```

https://github.com/samrith-s/parcel-plugin-structurize/blob/d4cc3a338fe6beda9f276d4be6d63243968f1c80/src/util.js#L1

Build is completed though.

**Comment by samrith-s** [comment]
Thank you for this. I will have a look into this the coming weekend. 

Could you provide some info on the version of Node and Parcel you are using?

**Comment by carscx** [comment]
Some solution?

**Comment by samrith-s** [comment]
@carscx If you could provide me with a reproducible repository, I'll be more than happy to look into it.
