### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by IsaacHub** [samrith-s/parcel-plugin-structurize#20]
While building I got the following warning:

```
(node:6268) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\projects\_draft\boilerplate-par
cel-master\dist\style.8f0dceae.css'

```
The file `style.8f0dceae.css` has been moved to `dist/css/` by this plugin and at the same time it's looking for the same file in `dist/` folder, and it says it's missing.

**Comment by samrith-s** [comment]
Can you provide a reproducible repository? AFAIK, this plugin is the last thing that runs. The error you are getting might be due to another plugin running after this.
