### ISSUE TITLE
Plugin does not transform links in .hbs files

### ISSUE THREAD

**Issue by TheComputerM** [samrith-s/parcel-plugin-structurize#22]

**Comment by TheComputerM** [comment]
This plugin does not transform entry points other than files with `.html` extension. I am using parcel-plugin-handlebars and the links in the transformed .hbs files still point to root.

**Comment by samrith-s** [comment]
Hmm, that's a difficult conundrum. I maybe add support for this in the future. I am thinking of completely rewriting this in v2 and providing more configuration options to the user.

Unfortunately, that is a little while away. Until then, you will have to bear with me. 😢

**Comment by TheComputerM** [comment]
You can add an option to change links in specified files only, this can also add support for react and vue

**Comment by samrith-s** [comment]
Yep, the plan is to add a new field which will be a glob. So you can specify something like:
```json
"baseFiles": "{.vue,.html,.hbs}"
```
