### ISSUE TITLE
[🐛] Bug: Corrupted images

### ISSUE THREAD

**Issue by cipri-p** [samrith-s/parcel-plugin-structurize#26]
## Describe the bug
I installed the plugin in one of my test projects and works ok for css, js, but it corrupts all the images I have in my project. The size of the (image) files are almost double in size after I run the build task.

## Error messages
no error messages in the console
## Expected behavior
the content of image files should be preserved

## Screenshots
n.a.

## Information
- Package version: 2.1.2
- Node version: 12.18.0

## Additional context
n.a.

**Comment by samrith-s** [comment]
Hey, I'll have a look into it. It's weird that that happens!

**Comment by samrith-s** [comment]
@cipri-p I have just released [v2.1.3](https://github.com/samrith-s/parcel-plugin-structurize/releases/tag/v2.1.3). Can you upgrade to this version and check if it works? I created a dummy and images no work fine for me.

**Comment by cipri-p** [comment]
@samrith-s thanks. Just had a look and images are ok with v2.1.3, however the references(in my index.html) don't seem to update with the new path.

**Comment by samrith-s** [comment]
Can you provide an example? It's a bit difficult to debug otherwise, coz all the tests are passing.
