### ISSUE TITLE
[🐛] Bug: Some assets not properly referenced

### ISSUE THREAD

**Issue by 3ub41r** [samrith-s/parcel-plugin-structurize#29]
Some of the assets are not properly referenced.

This is my `parcel-plugin-structurize.json` file:

```
{
    "rules": [
        {
            "match": "*.js",
            "folder": "js"
        },
        {
            "match": "*.css",
            "folder": "css"
        },
        {
            "match": "*.{jpg,jpeg,jpeg2,png,gif,svg,bmp,webp}",
            "folder": "images"
        }
    ]
}
```

## Expected behavior
I have configured the plugin to move `.css` files to the directory `css`. 

The files are moved appropriately, but when it is referenced from the HTML the directory is not taken into consideration. I have included a screenshot of the generated HTML to illustrate what I mean.

## Screenshots
This is the generated HTML.

![image](https://user-images.githubusercontent.com/7005315/103072786-39966000-4601-11eb-8b26-1f7749ef27c6.png)

## Information
- Package version: 2.3.1
- Node version: 12.5.0

Thanks for all your effort. I not very proficient in Javascript, sorry. Let me know if there is something I've missed.

**Comment by samrith-s** [comment]
Hello @xxidbr9 and @3ub41r thank you for the report!

Could you guys provide a minimal reproducible repository so I can debug it quicker? Sorry for the delayed response, I was on vacation.

**Comment by samrith-s** [comment]
> I'm facing the same bug when trying to build my projects
> 
> here my rules config on package.json
> ![image](https://user-images.githubusercontent.com/51733515/103660352-11fbac00-4fa0-11eb-9695-768168aa4d32.png)
> 
> and i got my css link are not correct
> ![image](https://user-images.githubusercontent.com/51733515/103660691-7c145100-4fa0-11eb-8f5f-5c753defca29.png)
> 
> Version: 2.3.1
> 
> Thanks btw

For this particular thing, can you try removing all `*.*.map`? The plugin automatically moves all the corresponding map files to the relevant directory. So the JS and CSS maps would be moved automatically. See the [second Gotcha](https://github.com/samrith-s/parcel-plugin-structurize#%EF%B8%8F-gotchas).

**Comment by samrith-s** [comment]
@3ub41r @xxidbr9 I tried both your config files, and everything works fine on my end. You can check it here:

<details>
<summary>@3ub41r output</summary>

Configuration:
```json
{
    "verbose": true,
    "displayAssetsMap": true,
    "rules": [
        {
            "match": "*.js",
            "folder": "js"
        },
        {
            "match": "*.css",
            "folder": "css"
        },
        {
            "match": "*.{jpg,jpeg,jpeg2,png,gif,svg,bmp,webp}",
            "folder": "images"
        }
    ]
}
```

HTML:
```html
<html>
    <head>
        <title>Parcel Plugin Structurize - Basic</title>
        <link rel="stylesheet" href="/css/main.3673b2a2.css" />
    </head>
    <body>
        Parcel plugin structurize test!
        <img src="/images/html-5-logo.18af91a1.webp" alt="HTML5 logo" width="150" />
        <p id="root"></p>
        <script src="/js/js.778fdcdf.js"></script>
    </body>
</html>
```

Output:
![image](https://user-images.githubusercontent.com/9032162/103960359-42834780-5152-11eb-8bf4-d354a953a9d1.png)

</details>

<details>
<summary>@xxidbr9 output</summary>

Configuration:
```json
{
    "verbose": true,
    "displayAssetsMap": true,
    "rules": [
        {
            "match": "*.{js,js.map}",
            "folder": "assets/js"
        },
        {
            "match": "*.{css,css.map}",
            "folder": "assets/css"
        },
        {
            "match": "*.{png,svg,jpg,jpg2,jpeg,gif,bmp,webm,webp}",
            "folder": "assets/img"
        }
    ]
}
```

HTML:
```html
<html>
    <head>
        <title>Parcel Plugin Structurize - Basic</title>
        <link rel="stylesheet" href="/assets/css/main.3673b2a2.css" />
    </head>
    <body>
        Parcel plugin structurize test!
        <img src="/assets/img/html-5-logo.18af91a1.webp" alt="HTML5 logo" width="150" />
        <p id="root"></p>
        <script src="/assets/js/js.778fdcdf.js"></script>
    </body>
</html>
```

Output:
![image](https://user-images.githubusercontent.com/9032162/103960603-d48b5000-5152-11eb-9a32-3803504186d1.png)

</details>

Are you guys using Windows by any chance?

**Comment by xxidbr9** [comment]
yes it fix, thanks alot 🎉👏🏻
