### ISSUE TITLE
[🐛] Bug: Path to asset gets updated only the first time

### ISSUE THREAD

**Issue by NicolasReibnitz** [samrith-s/parcel-plugin-structurize#36]
## Describe the bug
This is pretty straightforward: adding the same asset multiple times to an HTML file (for example) results in 404, because the path doesn't get updated globally.

```HTML
<img src="image.svg" />
<img src="image.svg" />
<img src="image.svg" />
```

becomes

```HTML
<img src="assets/image.c9a7e9b8.svg">
<img src="image.c9a7e9b8.svg">
<img src="image.c9a7e9b8.svg">
```

## Error messages

None.

## Expected behavior

The resulting index.html file should be updated globally:

```HTML
<img src="assets/image.c9a7e9b8.svg">
<img src="assets/image.c9a7e9b8.svg">
<img src="assets/image.c9a7e9b8.svg">
```
## Information
- Package version: v2.4.0
- Node version: v14.16.0

## Additional context
Please find a minimal test case here: https://github.com/NicolasReibnitz/simple-parcel-structure-test.

**Comment by samrith-s** [comment]
Hey sorry for this, I will review the PR asap! 😄
