### ISSUE TITLE
Public URL support

### ISSUE THREAD

**Issue by Immortalin** [samrith-s/parcel-plugin-structurize#4]
This is the build command: `parcel static/market/css/base.scss` with the following structurize config `"styles": {
            "match": "*.{css,css.map}",
            "folder": "static/market/js"
        },`
The Django app serves static folder on /static by default 
```
Source map error: request failed with status 404
Resource URL: http://localhost:4000/static/market/css/base.css
Source Map URL: /base.css.map
```

**Comment by samrith-s** [comment]
Hey, it has public url support already. It's a feature of Parcel itself.

You can use `--public-url` in the build command. So basically, you can change it like so:
```bash
parcel static/market/css/base.scss --public-url /static/
```

[Source](https://parceljs.org/cli.html#set-the-public-url-to-serve-on)

**Comment by samrith-s** [comment]
Closing due to no response.
