### ISSUE TITLE
CSS path in index.html is not set correctly (missing directory)

### ISSUE THREAD

**Issue by SC-JBG** [samrith-s/parcel-plugin-structurize#46]
Hi there,

I am facing an issue when running "parcel build". Apparently the paths required to correctly reference CSS stylesheets are not set correctly within the html file. 

Means, if I run

```
parcel build src/index.html
```

with the following config added to my package.json

```json
  "devDependencies": {
    "parcel-bundler": "^1.12.5",
    "parcel-plugin-clean-dist": "^0.0.6",
    "parcel-plugin-structurize": "^2.4.4",
    "sass": "^1.34.0"
  },
"parcel-plugin-structurize": {
  "verbose": true,
  "displayAssetsMap": true,
  "rules": [
    {
      "match": "*.{css,css.map}",
      "folder": "css"
    },
    {
      "match": "*.{js,js.map}",
      "folder": "js"
    },
    {
      "match": "*.{png,svg,jpg,jpg2,jpeg,gif,bmp,webm,webp}",
      "folder": "img"
    }
  ]
}
```

I expect my index.html to be rendered with the following references to *.css and *.js

```html
<link rel="stylesheet" href="/css/main.bb27b9fc.css">
...
<script src="/js/main.95ec2e8c.js"></script>
```

instead I am getting the following generated, JS looks fine but CSS is not referenced correctly (missing the css/ folder)

```html
<link rel="stylesheet" href="/main.bb27b9fc.css">
...
<script src="/js/main.95ec2e8c.js"></script>
```

My output from the build command looks like this

```shell
npm run build-prod

> main-app@1.0.0 build-prod
> parcel build src/index.html

⠋ Building...

✨  Built in 2.36s.

dist/main.95ec2e8c.js         1.24 KB    2.00s
dist/main.bb27b9fc.css.map      969 B      2ms
dist/main.95ec2e8c.js.map       875 B      0ms
dist/index.html                     786 B      8ms
dist/main.bb27b9fc.css          754 B    1.71s
  
  parcel-plugin-structurize
  Config: [AbsolutePathToProject]/package.json

  Assets Map:
  {
  '/index.html': {
    source: '[AbsolutePathToProject]/dist/index.html',
    destination: null,
    replacer: null,
    mapFile: false,
    dependents: [ '/main.95ec2e8c.js' ],
    config: undefined
  },
  '/main.95ec2e8c.js': {
    source: '[AbsolutePathToProject]/dist/main.95ec2e8c.js',
    destination: '[AbsolutePathToProject]/dist/js/main.95ec2e8c.js',
    replacer: '/js/main.95ec2e8c.js',
    mapFile: false,
    dependents: [ '/main.95ec2e8c.js.map', '/main.bb27b9fc.css' ],
    config: { match: '*.{js,js.map}', folder: 'js' }
  },
  '/main.95ec2e8c.js.map': {
    source: '[AbsolutePathToProject]/dist/main.95ec2e8c.js.map',
    destination: '[AbsolutePathToProject]/dist/js/main.95ec2e8c.js.map',
    replacer: '/js/main.95ec2e8c.js.map',
    mapFile: true,
    dependents: null,
    config: { match: '*.{js,js.map}', folder: 'js' }
  },
  '/main.bb27b9fc.css': {
    source: '[AbsolutePathToProject]/dist/main.bb27b9fc.css',
    destination: '[AbsolutePathToProject]/dist/css/main.bb27b9fc.css',
    replacer: '/css/main.bb27b9fc.css',
    mapFile: false,
    dependents: [ '/main.bb27b9fc.css.map' ],
    config: { match: '*.{css,css.map}', folder: 'css' }
  },
  '/main.bb27b9fc.css.map': {
    source: '[AbsolutePathToProject]/dist/main.bb27b9fc.css.map',
    destination: '[AbsolutePathToProject]/dist/css/main.bb27b9fc.css.map',
    replacer: '/css/main.bb27b9fc.css.map',
    mapFile: true,
    dependents: null,
    config: { match: '*.{css,css.map}', folder: 'css' }
  }
}

  Structurization complete. Modified 4 files in 6ms
  
   - Moved 2 files to dist/js
   - Moved 2 files to dist/css
  
  If you loved the plugin, do consider starring the repository:
  https://github.com/samrith-s/parcel-plugin-structurize
  
  Think something could be improved? Create an issue on our repository:
  http://bit.ly/parcel-plugin-structurize-feature-request
```

Any idea how this happened? Am I doing something wrong here?

Thanks a lot and take care,
best,
Jules

**Comment by samrith-s** [comment]
Hey :wave:, 

Can you paste your HTML file which references the CSS file?

**Comment by SC-JBG** [comment]
Hey @samrith-s ,

thanks for getting back to me, please find the HTML file down below. I stripped out everything unnecessary to keep it readable, head and script tags are as generated:

```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Hello, world!</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="">
		<link rel="stylesheet" href="/main.bb27b9fc.css">
	</head>
	<body>
		<h1>Hello, world!</h1>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin=""></script>
		<script src="/js/main.95ec2e8c.js"></script> 
	</body>
</html>
```

As you can see, the css-file is missing the "css" folder in its path and therefore leads to a 404.

Thank you for having a look at it and take care,
Jules

**Comment by samrith-s** [comment]
Hey @SC-JBG,

Thank you for that. I was actually asking for your entry file not the generated file.

That way, I can figure out what's happening!

**Comment by samrith-s** [comment]
Also, can you remove the `css.map` from the extension? There's a bit of a Gotcha around that. From the README:

> You should **NOT** add any structurizer rules for `.map` files as the plugin automatically resolves and restructures the sourcemap files to reside in the same directory as its parent. This can cause unintended side-effects.

**Comment by SC-JBG** [comment]
Hi @samrith-s ,

Oh, sorry, my bad.

Here is the original index.html that is my entry point:

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Hello, world!</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
	<h1>Hello, world!</h1>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
	<script src="js/main.js"></script>
</body>
</html>
```

And main.js content is just importing my SASS stylesheet:

```javascript
import "../scss/main.scss";
```

I have now removed *.map from the globs but without any change in behaviour.

Thank you and best,
Jules

**Comment by SC-JBG** [comment]
Alright, that was kinda help for self-help.
I recognized that I loaded my SCSS via JS - hence Parcel is generating a css file from it but still tries to load the SCSS vi JS through the main.js file - but as there is no SCSS folder available in my dist directory and I never copy over my SCSS files there is nothing to render. If I manually copy my SCSS sources over to dist, the style is loading as expected.

In addition, if I remove the SCSS import from my entry point JS and instead load the SCSS file directly in a link tag within my entry point HTML, the generation is correct, paths are looking good and everything runs as expected.

So my solution is to simply load SCSS in entry HTML like this:

```html
<link href="scss/crowdany.scss" rel="stylesheet">
```

which is a valid option according to https://parceljs.org/scss.html#usage

And remove the line below from my entry point JS file:

```javascript
import "../scss/main.scss";
```

I am just starting off with Parcel, I think that is simply my fault here not fully understanding how to work with Parcel and SASS. Hope that helps and probably saves you also some time.

Thank you for helping me out and take care,
Jules

**Comment by samrith-s** [comment]
Hey @SC-JBG , I am looking into this. Hopefully should have something concrete by tomorrow. :smile:

**Comment by SC-JBG** [comment]
Hey @samrith-s ,

wow you are fast mate :-)

Here are my dependencies, its pretty vanilla actually except for one plugin that I have loaded but actually don't really use anywhere:

```json
"devDependencies": {
    "parcel-bundler": "^1.12.5",
    "parcel-plugin-clean-dist": "^0.0.6",
    "parcel-plugin-structurize": "^2.4.4",
    "sass": "^1.34.0"
  }
```
