### ISSUE TITLE
[❔] Question: Directory structure is not being followed.

### ISSUE THREAD

**Issue by OrganizedFellow** [samrith-s/parcel-plugin-structurize#54]
This is my first time ever opening an issue, so I hope I am doing this correctly and providing enough feedback 👍 

## Question

I followed the [usage instructions](https://www.npmjs.com/package/parcel-plugin-structurize#-usage) as provided. But the folders I outlined in `parcel-plugin-structurize.json` are not being moved/copied over on `npm run build` command.

## My Version Information:
- Node version: v14.17.6
- Npm version: 7.24.1
- "parcel-plugin-structurize": "^2.4.4"
- "parcel": "^2.0.0-rc.0",

```
// parcel-plugin-structurize.json
{
    "rules": [
        {
            "match": "*.css",
            "folder": "src/css"
        },
        {
            "match": "*.{jpg,png,gif,svg}",
            "folder": "src/icons"
        },
        {
            "match": "*.{jpg,png,gif,svg}",
            "folder": "src/images"
        },
        {
            "match": "*.js",
            "folder": "src/js"
        }
    ]
}

```
This is what my structure looks like https://i.imgur.com/oktrIjF.png

The expectation was/is that your plugin maintains the same structure after running the `npm run build` command. This is what it looks like: 

```
  "scripts": {
    "dev": "npm-run-all --parallel dev:*",
    "dev:parcel": "parcel serve ./src/index.html",
    "dev:css": "tailwindcss -i src/css/tailwind.css -o src/css/styles.css -w",
    "build": "npm-run-all clean css parcel",
    "clean": "rm -rf dist/*",
    "css": "tailwindcss -i src/css/tailwind.css -o src/css/styles.css",
    "parcel": "parcel build src/index.html"
  },
```

After running `npm run build`, this is the resulting output https://i.imgur.com/q3GTLEk.png

Am I doing something wrong?

**Comment by samrith-s** [comment]
Hey @OrganizedFellow,

Thanks for the report. Unfortunately, this plugin only works for Parcel v1 and is not updated for v2 (yet).
