### ISSUE TITLE
Run on watch

### ISSUE THREAD

**Issue by Immortalin** [samrith-s/parcel-plugin-structurize#6]
This currently doesn't run in watch mode.

**Comment by Immortalin** [comment]
@samrith-s any suggestions for how to fix this?

**Comment by samrith-s** [comment]
Reopening till PR is merged. 

@Immortalin Please don't use `Closes x` in the title. Use it in the description.

**Comment by samrith-s** [comment]
Quick question, why is this needed in `watch` or `serve` mode? 

This is an expensive operation, as it traverses all the files and modifies them. When you watch, it'll happen every time Parcel builds. From the Parcel docs, even during `serve`, the bundler emits `buildEnd`. This plugin hooks on to that event, and runs once it the build has ended.

It would be a very bad idea to make it run on `watch` and `serve`, as it will do really expensive operations in the `dist` folder every time you do any modifications to any file watched by Parcel.

**Comment by samrith-s** [comment]
Closing due to no response.

**Comment by Immortalin** [comment]
Hi sorry I just noticed this. My reason for adding build mode is because if you are working with Web frameworks like Django etc. you need live loading support.

**Comment by samrith-s** [comment]
Hey

**Comment by Immortalin** [comment]
Hmm, then how do webpack et al. usually do it? Perhaps we can cache most of the ops?

**Comment by samrith-s** [comment]
Maybe we can, but that's an insane amount of heavy lifting for a plugin. It's not possible to do a compare operation on every save and update parts of the file. That's a task for the bundler to do, and would require a big overhaul. Should not be done within the scope of this plugin.

Alternatively, what we can do, is add the mode, but document it with a very clear warning about performance implications.

**Comment by Immortalin** [comment]
Sure that could work, feel free to modify the pull

**Comment by samrith-s** [comment]
I'm reopening your PR. But it has failed the Codacy tests. Please ensure your PR follows code quality standards, I'll review it then.

**Comment by Immortalin** [comment]
Send me the link to the failing test

**Comment by samrith-s** [comment]
It's on the PR itself. https://app.codacy.com/app/samrith/parcel-plugin-structurize/pullRequest?prid=3745658

**Comment by samrith-s** [comment]
Marking this as won't fix, as it is not in the scope of this plugin.
