### ISSUE TITLE
Does not work for multiple inputs

### ISSUE THREAD

**Issue by Immortalin** [samrith-s/parcel-plugin-structurize#7]
`parcel file1.html file2.js`

**Comment by Immortalin** [comment]
Hmmm, okay this may actually be rather difficult. Mutiple entry points in Parcel is [rather weird](https://github.com/parcel-bundler/parcel/issues/1778).

**Comment by samrith-s** [comment]
Yeah, this plugin is built for just hooking on to Parcel bundler. Works with everything Parcel provides. And, afaik, multiple entry points should also be taken into consideration.

Can you probably drop a minimum reproducible repository?

**Comment by samrith-s** [comment]
Closing due to no response.
